name: Integration Tests
on:
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Wait for Tests Results
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ secrets.NOTIFY_ORG }},
          repo: ${{ secrets.NOTIFY_REPO }},
          github_token: ${{ secrets.NOTIFY_PAT_TOKEN }}
          workflow_file_name: integration-tests
          ref: master
          client_payload: '{ "docsBranch": "${{ steps.branch-name.outputs.current_branch }}" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true