/usr/bin/docker run --name b3146df1e405457438b8332ae064943c65c_14b206 --label 294b31 --workdir /github/workspace --rm -e INPUT_OWNER -e INPUT_REPO -e INPUT_GITHUB_TOKEN -e INPUT_WORKFLOW_FILE_NAME -e INPUT_REF -e INPUT_CLIENT_PAYLOAD -e INPUT_PROPAGATE_FAILURE -e INPUT_TRIGGER_WORKFLOW -e INPUT_WAIT_WORKFLOW -e INPUT_GITHUB_USER -e INPUT_WAIT_INTERVAL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/docs/docs":"/github/workspace" 294b31:46df1e405457438b8332ae064943c65c

name: Integration Tests
on:
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests Results
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ secrets.NOTIFY_ORG }},
          repo: ${{ secrets.NOTIFY_REPO }},
          github_token: ${{ secrets.NOTIFY_PAT_TOKEN }}
          workflow_file_name: integration-tests.yml
          ref: master
          client_payload: '{ "inputs": { "docsBranch": "${{ steps.branch-name.outputs.current_branch }}" } }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true