name: Integration Tests
on:
  pull_request: {}

concurrency: 
  group: pr-integration-tests-${{ github.event.pull_request.id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Trigger Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests Results
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ secrets.NOTIFY_ORG }}
          repo: ${{ secrets.NOTIFY_REPO }}
          github_token: ${{ secrets.NOTIFY_PAT_TOKEN }}
          workflow_file_name: integration-tests.yml
          ref: master
          wait_interval: 90
          client_payload: '{ "docsBranch": "${{ github.ref.name }}", "pullRequest": "${{ github.event.pull_request.number }}" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
