name: Integration Tests
on:
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests Results
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ secrets.NOTIFY_ORG }},
          repo: ${{ secrets.NOTIFY_REPO }},
          github_token: ${{ secrets.NOTIFY_PAT_TOKEN }}
          workflow_file_name: integration-tests.yml
          ref: master
          client_payload: '{ "inputs": { "docsBranch": "${{ steps.branch-name.outputs.current_branch }}" } }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true